"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var authClient_1 = require("../clients/authClient");
var authService_1 = require("../services/authService");
var express = require("express");
var router = express.Router();
router.post("/login", authClient_1.logInUser, authService_1.handleAuthError);
router.post("/register", authClient_1.signUpNewUser, authService_1.handleAuthError);
router.post("/verifyNewUser", authClient_1.verifyNewUser, authService_1.handleAuthError);
router.post("/password/request-reset", authClient_1.requestPasswordReset, authService_1.handleAuthError);
router.post("/password/reset", authClient_1.changePassword, authService_1.handleAuthError);
router.get("/profile/:id", authClient_1.getProfile);
exports.default = router;
